apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: app
  labels:
    role: frontend
spec:
  containers:
  - name: frontend
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: app
  labels:
    role: backend
spec:
  containers:
  - name: backend
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: database
  namespace: app
  labels:
    role: database
spec:
  containers:
  - name: database
    image: nginx